---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS SAM CI CD - IAM

Resources:
  FileProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  FileProcessorRoleArn:
    Value: !GetAtt FileProcessorRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FileProcessorRoleArn
